package com.favorites.web;

import org.apache.poi.sl.usermodel.TextParagraph.TextAlign;
import org.apache.poi.xslf.usermodel.*;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import javax.servlet.http.HttpServletResponse;
import java.awt.*;
import java.io.IOException;
import java.io.OutputStream;

@Controller
@RequestMapping("/ppt")
public class PPTController {

    @GetMapping("/6g-evolution")
    public void download6GEvolutionPPT(HttpServletResponse response) throws IOException {
        XMLSlideShow ppt = new XMLSlideShow();
        XSLFSlide slide = ppt.createSlide();

        // Background
        XSLFBackground background = slide.getBackground();
        background.setFillColor(new Color(15, 23, 42)); // #0f172a

        // Title
        XSLFTextBox title = slide.createTextBox();
        title.setAnchor(new Rectangle(50, 30, 600, 50));
        XSLFTextParagraph p = title.addNewTextParagraph();
        XSLFTextRun r = p.addNewTextRun();
        r.setText("6G Evolution Strategy");
        r.setFontColor(new Color(56, 189, 248)); // #38bdf8
        r.setFontSize(36.0);
        r.setBold(true);

        // Subtitle
        XSLFTextBox subtitle = slide.createTextBox();
        subtitle.setAnchor(new Rectangle(50, 80, 600, 30));
        XSLFTextParagraph subP = subtitle.addNewTextParagraph();
        XSLFTextRun subR = subP.addNewTextRun();
        subR.setText("From Connectivity to Intelligent Sensing");
        subR.setFontColor(new Color(148, 163, 184)); // #94a3b8
        subR.setFontSize(18.0);

        // Content - Text Steps
        createStep(slide, 50, 150, "5G (2020)", "Foundation: eMBB, uRLLC, mMTC.\nPeak Rate: 10-20 Gbps. Latency: 1-5ms.");
        createStep(slide, 50, 250, "5G-Advanced (2025)", "Enhancement: AI/ML Integration, XR & Metaverse.\nUplink Centric Broadband.");
        createStep(slide, 50, 350, "6G (2030)", "Revolution: Integrated Sensing & Comm (ISAC).\nNative AI, Digital Twin. Peak: 1 Tbps.");

        // Graphic Area (Right side)
        // Draw Axis
        int graphX = 400;
        int graphY = 150;
        int graphW = 300;
        int graphH = 250;

        XSLFConnector xAxis = slide.createConnector();
        xAxis.setAnchor(new Rectangle(graphX, graphY + graphH, graphW, 0));
        xAxis.setLineColor(Color.GRAY);

        XSLFConnector yAxis = slide.createConnector();
        yAxis.setAnchor(new Rectangle(graphX, graphY, 0, graphH));
        yAxis.setLineColor(Color.GRAY);

        // Labels
        createLabel(slide, graphX, graphY + graphH + 10, "2020");
        createLabel(slide, graphX + graphW / 2, graphY + graphH + 10, "2025");
        createLabel(slide, graphX + graphW, graphY + graphH + 10, "2030");

        // Curves (Simulated with simple lines/shapes for simplicity in POI)
        // Curve 1: Network Capacity (Blue)
        drawCurve(slide, graphX, graphY + graphH, graphX + graphW, graphY + 50, new Color(56, 189, 248));
        createLabel(slide, graphX + graphW + 10, graphY + 50, "Capacity", new Color(56, 189, 248));

        // Curve 2: AI Integration (Purple)
        drawCurve(slide, graphX, graphY + graphH, graphX + graphW, graphY + 20, new Color(129, 140, 248));
        createLabel(slide, graphX + graphW + 10, graphY + 20, "AI Native", new Color(129, 140, 248));

        // Gemini Badge
        XSLFTextBox badge = slide.createTextBox();
        badge.setAnchor(new Rectangle(graphX + graphW - 150, graphY - 20, 150, 30));
        XSLFTextParagraph badgeP = badge.addNewTextParagraph();
        badgeP.setTextAlign(TextAlign.RIGHT);
        XSLFTextRun badgeR = badgeP.addNewTextRun();
        badgeR.setText("Generated by Gemini 3");
        badgeR.setFontColor(new Color(165, 180, 252));
        badgeR.setFontSize(10.0);
        badgeR.setItalic(true);

        // Footer
        XSLFTextBox footer = slide.createTextBox();
        footer.setAnchor(new Rectangle(50, 500, 600, 20));
        XSLFTextParagraph footerP = footer.addNewTextParagraph();
        XSLFTextRun footerR = footerP.addNewTextRun();
        footerR.setText("Confidential - Internal Use Only | Source: Global Telecommunications Standards 2026");
        footerR.setFontColor(Color.GRAY);
        footerR.setFontSize(10.0);

        // Send response
        response.setContentType("application/vnd.openxmlformats-officedocument.presentationml.presentation");
        response.setHeader("Content-Disposition", "attachment; filename=6g-evolution-insight.pptx");
        
        try (OutputStream out = response.getOutputStream()) {
            ppt.write(out);
        }
    }

    private void createStep(XSLFSlide slide, int x, int y, String title, String desc) {
        XSLFTextBox box = slide.createTextBox();
        box.setAnchor(new Rectangle(x, y, 300, 80));
        
        XSLFTextParagraph p1 = box.addNewTextParagraph();
        XSLFTextRun r1 = p1.addNewTextRun();
        r1.setText(title);
        r1.setFontColor(new Color(226, 232, 240));
        r1.setFontSize(16.0);
        r1.setBold(true);

        XSLFTextParagraph p2 = box.addNewTextParagraph();
        XSLFTextRun r2 = p2.addNewTextRun();
        r2.setText(desc);
        r2.setFontColor(new Color(203, 213, 225));
        r2.setFontSize(12.0);
    }

    private void createLabel(XSLFSlide slide, int x, int y, String text) {
        createLabel(slide, x, y, text, Color.GRAY);
    }

    private void createLabel(XSLFSlide slide, int x, int y, String text, Color color) {
        XSLFTextBox box = slide.createTextBox();
        box.setAnchor(new Rectangle(x, y, 100, 30));
        XSLFTextParagraph p = box.addNewTextParagraph();
        XSLFTextRun r = p.addNewTextRun();
        r.setText(text);
        r.setFontColor(color);
        r.setFontSize(10.0);
    }

    private void drawCurve(XSLFSlide slide, int x1, int y1, int x2, int y2, Color color) {
        // Approximating curve with a line for simplicity in this generated PPT
        XSLFConnector line = slide.createConnector();
        // Bounding box for the line
        // We want to draw from (x1, y1) to (x2, y2)
        // Since y1 (bottom) > y2 (top) in screen coords, this is a "slash" / shape
        // Default diagonal is \ (top-left to bottom-right)
        // So we need to flip vertical to get /
        
        line.setAnchor(new Rectangle(x1, y2, x2 - x1, y1 - y2));
        line.setFlipVertical(true); 
        
        line.setLineColor(color);
        line.setLineWidth(3.0);
    }
}
